version: '3.8'
services:
  postgres:
    container_name: pg_container
    image: postgres:14-th_TH
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "15432:5432"
    volumes:
      - "D:/Docker/postgres/data:/var/lib/postgresql/data"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "15050:80"